DEFAULT_CHAT_TEMPLATE = (  # LLAMA3.1 used template
    "{% set loop_messages = messages %}"
    "{% for message in loop_messages %}"
    "{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}"
    "{% if loop.index0 == 0 %}"
    "{% set content = bos_token + content %}{% endif %}"
    "{{ content }}{% endfor %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}"
)

DEFAULT_RESPONSE_TEMPLATE = '<|start_header_id|>assistant<|end_header_id|>\n\n'

LLAMA_3_TEMPLATE_NO_SYSTEM = ("{{- bos_token }}\n"
                              "{%- if custom_tools is defined %}\n"
                              "    {%- set tools = custom_tools %}\n"
                              "{%- endif %}\n"
                              "{%- if not tools_in_user_message is defined %}\n"
                              "    {%- set tools_in_user_message = true %}\n"
                              "{%- endif %}\n"
                              "{%- if not tools is defined %}\n"
                              "    {%- set tools = none %}\n"
                              "{%- endif %}\n\n"
                              "{#- Custom tools are passed in a user message with some extra guidance #}\n"
                              "{%- if tools_in_user_message and not tools is none %}\n"
                              "    {#- Extract the first user message so we can plug it in here #}\n"
                              "    {%- if messages | length != 0 %}\n"
                              "        {%- set first_user_message = messages[0]['content']|trim %}\n"
                              "        {%- set messages = messages[1:] %}\n"
                              "    {%- else %}\n"
                              "        {{- raise_exception(\"Cannot put tools in the first user message when there's no first user message!\") }}\n"
                              "    {%- endif %}\n"
                              "    {{- '<|start_header_id|>user<|end_header_id|>\\n\\n' -}}\n"
                              "    {{- \"Given the following functions, please respond with a JSON for a function call \" }}\n"
                              "    {{- \"with its proper arguments that best answers the given prompt.\\n\\n\" }}\n"
                              "    {{- 'Respond in the format {\"name\": function name, \"parameters\": dictionary of argument name and its value}.' }}\n"
                              "    {{- \"Do not use variables.\\n\\n\" }}\n"
                              "    {%- for t in tools %}\n"
                              "        {{- t | tojson(indent=4) }}\n"
                              "        {{- \"\\n\\n\" }}\n"
                              "    {%- endfor %}\n"
                              "    {{- first_user_message + \"<|eot_id|>\"}}\n"
                              "{%- endif %}\n\n"
                              "{%- for message in messages %}\n"
                              "    {%- if not (message.role == 'ipython' or message.role == 'tool' or 'tool_calls' in message) %}\n"
                              "        {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\\n\\n'+ message['content'] | trim + '<|eot_id|>' }}\n"
                              "    {%- elif 'tool_calls' in message %}\n"
                              "        {%- if not message.tool_calls|length == 1 %}\n"
                              "            {{- raise_exception(\"This model only supports single tool-calls at once!\") }}\n"
                              "        {%- endif %}\n"
                              "        {%- set tool_call = message.tool_calls[0].function %}\n"
                              "        {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' -}}\n"
                              "        {{- '{\"name\": \"' + tool_call.name + '\", ' }}\n"
                              "        {{- '\"parameters\": ' }}\n"
                              "        {{- tool_call.arguments | tojson }}\n"
                              "        {{- \"}\" }}\n"
                              "        {{- \"<|eot_id|>\" }}\n"
                              "    {%- elif message.role == \"tool\" or message.role == \"ipython\" %}\n"
                              "        {{- \"<|start_header_id|>ipython<|end_header_id|>\\n\\n\" }}\n"
                              "        {%- if message.content is mapping or message.content is iterable %}\n"
                              "            {{- message.content | tojson }}\n"
                              "        {%- else %}\n"
                              "            {{- message.content }}\n"
                              "        {%- endif %}\n"
                              "        {{- \"<|eot_id|>\" }}\n"
                              "    {%- endif %}\n"
                              "{%- endfor %}\n"
                              "{%- if add_generation_prompt %}\n"
                              "    {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' }}\n"
                              "{%- endif %}\n")
