from mmotion.utils.task.modality import MOTION_HOLDER, INTERACTOR_MOTION_HOLDER, UNION_CAPTION_HOLDER

IM2T_TEMPLATE = [
    {"input": f"{MOTION_HOLDER}, {INTERACTOR_MOTION_HOLDER}. What are these 2 people doing?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The first person moves like this: {MOTION_HOLDER}, while the second: {INTERACTOR_MOTION_HOLDER}, what are they doint?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Person A: {MOTION_HOLDER}, Person B: {INTERACTOR_MOTION_HOLDER}. What is happening here?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Actions: {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. Describe the scene.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What's going on?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Action sequence: {MOTION_HOLDER}, {INTERACTOR_MOTION_HOLDER}. What does this represent?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The movements are {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What is the context?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} for the first person, {INTERACTOR_MOTION_HOLDER} for the second. Explain.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"With {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}, what activity is depicted?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Person one does {MOTION_HOLDER}, person two does {INTERACTOR_MOTION_HOLDER}. What is occurring?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the scenario where {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} are performed.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} are taking place. What are they doing?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What is the scene with {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Given the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}, describe the event.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} happens first, then {INTERACTOR_MOTION_HOLDER}. What is the situation?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The first action is {MOTION_HOLDER}, followed by {INTERACTOR_MOTION_HOLDER}. What is happening?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the interaction: {MOTION_HOLDER}, then {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does the sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} depict?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Given {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}, what is being done?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the actions: {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the event with actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The movements {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} occur. What is the activity?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the context of {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What scenario involves {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} are observed. Describe the situation.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} represent?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"With {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}, what is happening?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe what is happening: {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} occur. What does this show?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What are the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} depicting?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"First action: {MOTION_HOLDER}, second action: {INTERACTOR_MOTION_HOLDER}. What is the scene?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. Describe the event.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What is taking place with {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the actions: {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What activity is this?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What scene does {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} describe?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions are {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. Explain.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Sequence: {MOTION_HOLDER}, followed by {INTERACTOR_MOTION_HOLDER}. What is occurring?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the scenario with actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What does this represent?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} actions are performed. What is happening?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Actions: {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. Describe the event.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The sequence of {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} represents what?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What activity involves {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the actions happening: {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"{MOTION_HOLDER} occurs first, then {INTERACTOR_MOTION_HOLDER}. What is being depicted?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain what {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} are doing.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The movements of {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What do they signify?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What do the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} describe?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}. What is being shown?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the scene with {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Sequence of actions: {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. What is happening?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does the sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} show?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe what {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} are doing.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. Explain the scenario.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the context of {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does the action sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} depict?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Actions observed: {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. What is the scene?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What is happening with the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The sequence of actions {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. What is taking place?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What scenario is depicted with {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The movements of {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}. What is being shown?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What activity do the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} describe?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the event with the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions are {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. What is depicted?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does the sequence of actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} represent?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the scene involving {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What is happening in the sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}. Describe the event.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What scenario involves the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The movements {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What is shown here?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What does the sequence of actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} describe?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions are {MOTION_HOLDER} followed by {INTERACTOR_MOTION_HOLDER}. Explain the scene.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the context of {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Sequence of {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What is occurring?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The sequence of actions is {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What is happening?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain the scenario with the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The actions are {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}. Describe the scene.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What is the context of the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Explain what is happening: {MOTION_HOLDER} and then {INTERACTOR_MOTION_HOLDER}.",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"The sequence {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}. What does it show?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"What activity is represented by the actions {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER}?",
     "output": f"{UNION_CAPTION_HOLDER}"},
    {"input": f"Describe the event where {MOTION_HOLDER} and {INTERACTOR_MOTION_HOLDER} occur.",
     "output": f"{UNION_CAPTION_HOLDER}"},
]