from mmotion.utils.task.modality import MUSIC_HOLDER, MOTION_HOLDER

D2M_TEMPLATE = [
    {"input": f"Compose music for this dance. {MOTION_HOLDER}",
     "output": f"This is a piece of music composed lying down. {MUSIC_HOLDER}"},
    {"input": f"What kind of music goes well with this dance? {MOTION_HOLDER}",
     "output": f"Perhaps, {MUSIC_HOLDER} would be a good fit."},
    {"input": f"Try adding background music to this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER}"},
    {"input": f"Suggest a tune for this particular dance style. {MOTION_HOLDER}",
     "output": f"I think {MUSIC_HOLDER} would complement it well."},
    {"input": f"Create a soundtrack for the following dance. {MOTION_HOLDER}",
     "output": f"This music would work well: {MUSIC_HOLDER}"},
    {"input": f"What music fits this dance routine? {MOTION_HOLDER}",
     "output": f"I suggest {MUSIC_HOLDER} as a match."},
    {"input": f"Compose a melody to match these dance moves. {MOTION_HOLDER}",
     "output": f"This melody might fit: {MUSIC_HOLDER}"},
    {"input": f"Provide a fitting piece of music for this dance performance. {MOTION_HOLDER}",
     "output": f"A fitting piece might be: {MUSIC_HOLDER}"},
    {"input": f"Match this dance sequence with suitable music. {MOTION_HOLDER}",
     "output": f"Perhaps this track: {MUSIC_HOLDER} would work."},
    {"input": f"What type of music would go with this choreography? {MOTION_HOLDER}",
     "output": f"I think {MUSIC_HOLDER} fits well."},
    {"input": f"Pair some music with this dance. {MOTION_HOLDER}",
     "output": f"This music would pair nicely: {MUSIC_HOLDER}"},
    {"input": f"Suggest a song for this dance routine. {MOTION_HOLDER}",
     "output": f"How about this one: {MUSIC_HOLDER}"},
    {"input": f"Find music that complements this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} might be a good complement."},
    {"input": f"Generate music for these dance movements. {MOTION_HOLDER}",
     "output": f"The music could be: {MUSIC_HOLDER}"},
    {"input": f"Which tune would go well with this dance performance? {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could be a perfect fit."},
    {"input": f"Add a musical track to this choreography. {MOTION_HOLDER}",
     "output": f"This track might work: {MUSIC_HOLDER}"},
    {"input": f"Choose music that matches the mood of this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} would set the right mood."},
    {"input": f"Suggest background music for this dance piece. {MOTION_HOLDER}",
     "output": f"The background music could be: {MUSIC_HOLDER}"},
    {"input": f"Find a song that suits this dance. {MOTION_HOLDER}",
     "output": f"I think {MUSIC_HOLDER} would suit it well."},
    {"input": f"What soundtrack would go with this dance? {MOTION_HOLDER}",
     "output": f"The soundtrack might be: {MUSIC_HOLDER}"},
    {"input": f"Create a musical score for this dance. {MOTION_HOLDER}",
     "output": f"This score could match: {MUSIC_HOLDER}"},
    {"input": f"Provide a song that would enhance this dance performance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could enhance the performance."},
    {"input": f"What music would you choose for this choreography? {MOTION_HOLDER}",
     "output": f"I'd choose {MUSIC_HOLDER}."},
    {"input": f"Compose a song to fit these dance moves. {MOTION_HOLDER}",
     "output": f"Here's a song that fits: {MUSIC_HOLDER}"},
    {"input": f"Match these movements with a suitable soundtrack. {MOTION_HOLDER}",
     "output": f"The soundtrack might be: {MUSIC_HOLDER}"},
    {"input": f"Find a melody that would accompany this dance. {MOTION_HOLDER}",
     "output": f"This melody would accompany it well: {MUSIC_HOLDER}"},
    {"input": f"Provide music for this set of dance moves. {MOTION_HOLDER}",
     "output": f"The music could be: {MUSIC_HOLDER}"},
    {"input": f"Suggest a track for this dance sequence. {MOTION_HOLDER}",
     "output": f"How about this track: {MUSIC_HOLDER}"},
    {"input": f"What kind of music would suit this performance? {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} seems suitable."},
    {"input": f"Compose a tune to go along with this dance. {MOTION_HOLDER}",
     "output": f"This tune might go well: {MUSIC_HOLDER}"},
    {"input": f"Create music that pairs with these dance movements. {MOTION_HOLDER}",
     "output": f"The paired music could be: {MUSIC_HOLDER}"},
    {"input": f"What song complements this set of dance moves? {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} would complement it nicely."},
    {"input": f"Find a soundtrack that fits this dance. {MOTION_HOLDER}",
     "output": f"The soundtrack could be: {MUSIC_HOLDER}"},
    {"input": f"Generate a melody that works well with these dance movements. {MOTION_HOLDER}",
     "output": f"This melody works: {MUSIC_HOLDER}"},
    {"input": f"Provide music that would suit this choreography. {MOTION_HOLDER}",
     "output": f"The suitable music is: {MUSIC_HOLDER}"},
    {"input": f"What track would go well with this dance routine? {MOTION_HOLDER}",
     "output": f"The track could be: {MUSIC_HOLDER}"},
    {"input": f"Pick a song that fits the mood of this dance. {MOTION_HOLDER}",
     "output": f"The song might be: {MUSIC_HOLDER}"},
    {"input": f"Suggest a piece of music that matches this dance. {MOTION_HOLDER}",
     "output": f"This piece of music fits: {MUSIC_HOLDER}"},
    {"input": f"Add a musical composition that fits these movements. {MOTION_HOLDER}",
     "output": f"The composition might be: {MUSIC_HOLDER}"},
    {"input": f"Find a melody to match this choreography. {MOTION_HOLDER}",
     "output": f"The matching melody is: {MUSIC_HOLDER}"},
    {"input": f"Choose music that accompanies this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could be a good accompaniment."},
    {"input": f"Create a piece of music for these dance moves. {MOTION_HOLDER}",
     "output": f"The music might be: {MUSIC_HOLDER}"},
    {"input": f"Provide background music for this performance. {MOTION_HOLDER}",
     "output": f"The background music could be: {MUSIC_HOLDER}"},
    {"input": f"Generate a soundtrack that fits the following dance. {MOTION_HOLDER}",
     "output": f"The fitting soundtrack is: {MUSIC_HOLDER}"},
    {"input": f"Compose a melody that complements this dance. {MOTION_HOLDER}",
     "output": f"This melody could complement it: {MUSIC_HOLDER}"},
    {"input": f"What kind of soundtrack would fit these movements? {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could fit well."},
    {"input": f"Match a song with this choreography. {MOTION_HOLDER}",
     "output": f"The matching song could be: {MUSIC_HOLDER}"},
    {"input": f"Find a piece of music to accompany this dance. {MOTION_HOLDER}",
     "output": f"The accompanying music might be: {MUSIC_HOLDER}"},
    {"input": f"Create music that works well with these dance steps. {MOTION_HOLDER}",
     "output": f"The music that works well is: {MUSIC_HOLDER}"},
    {"input": f"Generate a song to go along with this dance. {MOTION_HOLDER}",
     "output": f"The song is: {MUSIC_HOLDER}"},
    {"input": f"What kind of music should be paired with this dance? {MOTION_HOLDER}",
     "output": f"This music should be paired: {MUSIC_HOLDER}"},
    {"input": f"Compose music that fits these dance steps. {MOTION_HOLDER}",
     "output": f"This music could fit: {MUSIC_HOLDER}"},
    {"input": f"Provide a piece of music that goes with this dance. {MOTION_HOLDER}",
     "output": f"The music is: {MUSIC_HOLDER}"},
    {"input": f"Choose a track that matches this dance style. {MOTION_HOLDER}",
     "output": f"This track might match: {MUSIC_HOLDER}"},
    {"input": f"Pick music that complements this dance routine. {MOTION_HOLDER}",
     "output": f"The music could be: {MUSIC_HOLDER}"},
    {"input": f"What kind of song would fit these dance moves? {MOTION_HOLDER}",
     "output": f"I think {MUSIC_HOLDER} would fit well."},
    {"input": f"Generate a score that goes with this choreography. {MOTION_HOLDER}",
     "output": f"The score could be: {MUSIC_HOLDER}"},
    {"input": f"What piece of music would you add to these dance steps? {MOTION_HOLDER}",
     "output": f"The music would be: {MUSIC_HOLDER}"},
    {"input": f"Compose a fitting track for this choreography. {MOTION_HOLDER}",
     "output": f"The track could be: {MUSIC_HOLDER}"},
    {"input": f"Suggest music that would enhance this performance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could enhance it well."},
    {"input": f"Match a musical composition to this dance. {MOTION_HOLDER}",
     "output": f"The composition might be: {MUSIC_HOLDER}"},
    {"input": f"Create a melody that suits this dance performance. {MOTION_HOLDER}",
     "output": f"The melody could be: {MUSIC_HOLDER}"},
    {"input": f"What type of music would go well with this performance? {MOTION_HOLDER}",
     "output": f"The music could be: {MUSIC_HOLDER}"},
    {"input": f"Compose a soundtrack for the following choreography. {MOTION_HOLDER}",
     "output": f"The soundtrack could be: {MUSIC_HOLDER}"},
    {"input": f"Create a melody for this set of movements. {MOTION_HOLDER}",
     "output": f"The melody might be: {MUSIC_HOLDER}"},
    {"input": f"What track could you add to this dance? {MOTION_HOLDER}", "output": f"I'd add {MUSIC_HOLDER}."},
    {"input": f"Generate a fitting tune for this choreography. {MOTION_HOLDER}",
     "output": f"The tune might be: {MUSIC_HOLDER}"},
    {"input": f"Compose music that fits this dance routine. {MOTION_HOLDER}",
     "output": f"The music would be: {MUSIC_HOLDER}"},
    {"input": f"What piece of music fits this dance style? {MOTION_HOLDER}", "output": f"I think {MUSIC_HOLDER} fits."},
    {"input": f"Choose music that pairs well with this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} would pair well."},
    {"input": f"Find a piece of music to match this choreography. {MOTION_HOLDER}",
     "output": f"The music might be: {MUSIC_HOLDER}"},
    {"input": f"Create a musical score to go with this dance. {MOTION_HOLDER}",
     "output": f"The score could be: {MUSIC_HOLDER}"},
    {"input": f"Provide music that accompanies this dance routine. {MOTION_HOLDER}",
     "output": f"The music could accompany it: {MUSIC_HOLDER}"},
    {"input": f"Match this dance with an appropriate tune. {MOTION_HOLDER}",
     "output": f"The tune might be: {MUSIC_HOLDER}"},
    {"input": f"Suggest music that could fit this choreography. {MOTION_HOLDER}",
     "output": f"This music could fit: {MUSIC_HOLDER}"},
    {"input": f"Generate a track to pair with these movements. {MOTION_HOLDER}",
     "output": f"The paired track is: {MUSIC_HOLDER}"},
    {"input": f"Compose a melody to accompany this dance. {MOTION_HOLDER}",
     "output": f"The melody might be: {MUSIC_HOLDER}"},
    {"input": f"Provide a musical track for this performance. {MOTION_HOLDER}",
     "output": f"The track could be: {MUSIC_HOLDER}"},
    {"input": f"Match these dance movements with a soundtrack. {MOTION_HOLDER}",
     "output": f"The soundtrack might be: {MUSIC_HOLDER}"},
    {"input": f"Choose a piece of music to complement this dance. {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} could complement it."},
    {"input": f"What music would fit these dance steps? {MOTION_HOLDER}",
     "output": f"{MUSIC_HOLDER} might fit the steps."},
    {"input": f"Suggest a tune to match this choreography. {MOTION_HOLDER}",
     "output": f"This tune might match: {MUSIC_HOLDER}"},
    {"input": f"Provide a soundtrack that suits this set of dance moves. {MOTION_HOLDER}",
     "output": f"The soundtrack might be: {MUSIC_HOLDER}"},
    {"input": f"Generate music that fits this dance performance. {MOTION_HOLDER}",
     "output": f"The fitting music is: {MUSIC_HOLDER}"},
    {"input": f"What melody could fit these dance movements? {MOTION_HOLDER}",
     "output": f"This melody could fit: {MUSIC_HOLDER}"},
    {"input": f"Suggest a composition that pairs with this choreography. {MOTION_HOLDER}",
     "output": f"The composition could be: {MUSIC_HOLDER}"},
    {"input": f"Pick a track to match this dance. {MOTION_HOLDER}", "output": f"The track might be: {MUSIC_HOLDER}"},
    {"input": f"Choose music that enhances this dance performance. {MOTION_HOLDER}",
     "output": f"The music might enhance it: {MUSIC_HOLDER}"}
]
