"""
    Prompt for music2dance task involving aist++ and cs3d dataset
"""
from mmotion.utils.task.modality import MUSIC_HOLDER, MOTION_HOLDER

M2D_TEMPLATE = [
    {"input": f"Dance to the music: {MUSIC_HOLDER}",
     "output": f"Okay, i will dance to the music: {MOTION_HOLDER}"},
    {"input": f"Match this piece of music with a dance {MUSIC_HOLDER}.",
     "output": f"{MOTION_HOLDER}"},
    {"input": f"Listen to this music and show the matching dance: {MUSIC_HOLDER}",
     "output": f"The dance for this music would look like this: {MOTION_HOLDER}"},
    {"input": f"Here's a song. What kind of dance would go with it? {MUSIC_HOLDER}",
     "output": f"The dance would look like this: {MOTION_HOLDER}"},
    {"input": f"Play the music: {MUSIC_HOLDER}. How would you dance to it?",
     "output": f"This is how the dance might look: {MOTION_HOLDER}"},
    {"input": f"Listen to this music and create a dance: {MUSIC_HOLDER}",
     "output": f"The corresponding dance moves are: {MOTION_HOLDER}"},
    {"input": f"Match a dance to this music track: {MUSIC_HOLDER}",
     "output": f"This is the dance for it: {MOTION_HOLDER}"},
    {"input": f"What kind of dance would fit this song? {MUSIC_HOLDER}",
     "output": f"The dance would look like: {MOTION_HOLDER}"},
    {"input": f"Can you match a dance to this song? {MUSIC_HOLDER}",
     "output": f"Sure! The dance would be: {MOTION_HOLDER}"},
    {"input": f"Create a dance for the following music: {MUSIC_HOLDER}",
     "output": f"This is the dance you might perform: {MOTION_HOLDER}"},
    {"input": f"Generate a dance for this piece of music: {MUSIC_HOLDER}",
     "output": f"The dance is generated as follows: {MOTION_HOLDER}"},
    {"input": f"Dance moves for this track: {MUSIC_HOLDER}",
     "output": f"The moves could look like this: {MOTION_HOLDER}"},
    {"input": f"This is a piece of music: {MUSIC_HOLDER}. How would you dance to it?",
     "output": f"Here is a possible dance: {MOTION_HOLDER}"},
    {"input": f"Listen to this song: {MUSIC_HOLDER}. What dance would match?",
     "output": f"The matching dance might be: {MOTION_HOLDER}"},
    {"input": f"What kind of movements would go with this music? {MUSIC_HOLDER}",
     "output": f"The movements could be like this: {MOTION_HOLDER}"},
    {"input": f"Play the music and imagine a dance: {MUSIC_HOLDER}",
     "output": f"This is the imagined dance: {MOTION_HOLDER}"},
    {"input": f"Based on this audio, create a dance: {MUSIC_HOLDER}",
     "output": f"The dance creation looks like this: {MOTION_HOLDER}"},
    {"input": f"Show me the dance that fits this music: {MUSIC_HOLDER}",
     "output": f"The dance could be like this: {MOTION_HOLDER}"},
    {"input": f"Here is a melody: {MUSIC_HOLDER}. How would you dance to it?",
     "output": f"This is how the dance might unfold: {MOTION_HOLDER}"},
    {"input": f"Match a dance sequence to the following tune: {MUSIC_HOLDER}",
     "output": f"The dance sequence might look like this: {MOTION_HOLDER}"},
    {"input": f"Listen to the melody: {MUSIC_HOLDER}. How do you move to it?",
     "output": f"You might move like this: {MOTION_HOLDER}"},
    {"input": f"Create a set of dance movements for this song: {MUSIC_HOLDER}",
     "output": f"The dance set looks like this: {MOTION_HOLDER}"},
    {"input": f"Dance along to the music: {MUSIC_HOLDER}",
     "output": f"The dance moves along like this: {MOTION_HOLDER}"},
    {"input": f"What are the dance steps for this song? {MUSIC_HOLDER}",
     "output": f"The dance steps would be: {MOTION_HOLDER}"},
    {"input": f"Match a choreographed routine to this music: {MUSIC_HOLDER}",
     "output": f"The choreography might look like this: {MOTION_HOLDER}"},
    {"input": f"How would someone dance to this track? {MUSIC_HOLDER}",
     "output": f"They might dance like this: {MOTION_HOLDER}"},
    {"input": f"Here's a music clip: {MUSIC_HOLDER}. Can you create a dance for it?",
     "output": f"Yes, here is the dance: {MOTION_HOLDER}"},
    {"input": f"Create a dance routine for this tune: {MUSIC_HOLDER}",
     "output": f"The dance routine could be like this: {MOTION_HOLDER}"},
    {"input": f"How do you think someone might dance to this piece? {MUSIC_HOLDER}",
     "output": f"They might dance like this: {MOTION_HOLDER}"},
    {"input": f"Generate dance moves that go with this music: {MUSIC_HOLDER}",
     "output": f"Here are the generated moves: {MOTION_HOLDER}"},
    {"input": f"Match some dance steps to the following sound: {MUSIC_HOLDER}",
     "output": f"The steps could be like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this song and perform a dance: {MUSIC_HOLDER}",
     "output": f"The performance might be: {MOTION_HOLDER}"},
    {"input": f"Show a dance sequence for this track: {MUSIC_HOLDER}",
     "output": f"The sequence might look like: {MOTION_HOLDER}"},
    {"input": f"Match dance movements with this piece: {MUSIC_HOLDER}",
     "output": f"The matching movements are: {MOTION_HOLDER}"},
    {"input": f"Can you come up with a dance for this music? {MUSIC_HOLDER}",
     "output": f"Here is the dance: {MOTION_HOLDER}"},
    {"input": f"Listen to the song and create a dance routine: {MUSIC_HOLDER}",
     "output": f"The dance routine might look like this: {MOTION_HOLDER}"},
    {"input": f"How would a dancer move to this song? {MUSIC_HOLDER}",
     "output": f"The dancer's moves could be: {MOTION_HOLDER}"},
    {"input": f"Create a dance style for this music: {MUSIC_HOLDER}",
     "output": f"The dance style could be like: {MOTION_HOLDER}"},
    {"input": f"This is the song: {MUSIC_HOLDER}. How might someone dance to it?",
     "output": f"Someone might dance like this: {MOTION_HOLDER}"},
    {"input": f"Listen to the music and design a dance: {MUSIC_HOLDER}",
     "output": f"The designed dance looks like this: {MOTION_HOLDER}"},
    {"input": f"Here's a song. How might a dancer move to this? {MUSIC_HOLDER}",
     "output": f"The dancer might move like this: {MOTION_HOLDER}"},
    {"input": f"Generate dance steps for this piece: {MUSIC_HOLDER}",
     "output": f"The generated steps are: {MOTION_HOLDER}"},
    {"input": f"Create a set of dance steps to fit this song: {MUSIC_HOLDER}",
     "output": f"The set of steps looks like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this audio and think of a dance: {MUSIC_HOLDER}",
     "output": f"The dance could be: {MOTION_HOLDER}"},
    {"input": f"Show the dance choreography for this music: {MUSIC_HOLDER}",
     "output": f"The choreography might look like: {MOTION_HOLDER}"},
    {"input": f"Play this track: {MUSIC_HOLDER}. What dance moves fit this song?",
     "output": f"The dance moves that fit are: {MOTION_HOLDER}"},
    {"input": f"Here's a piece of music. What dance might be performed to it? {MUSIC_HOLDER}",
     "output": f"The dance might be performed like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this tune and imagine a dance: {MUSIC_HOLDER}",
     "output": f"The imagined dance might be: {MOTION_HOLDER}"},
    {"input": f"Play the song: {MUSIC_HOLDER}. What kind of dance steps would you create?",
     "output": f"The steps might look like: {MOTION_HOLDER}"},
    {"input": f"This is a musical track: {MUSIC_HOLDER}. Show the corresponding dance.",
     "output": f"The corresponding dance might be: {MOTION_HOLDER}"},
    {"input": f"How would you move to this music? {MUSIC_HOLDER}",
     "output": f"The movements would look like: {MOTION_HOLDER}"},
    {"input": f"Listen to this music track: {MUSIC_HOLDER}. What kind of dance routine fits?",
     "output": f"The dance routine fits like this: {MOTION_HOLDER}"},
    {"input": f"Create a dance performance based on this song: {MUSIC_HOLDER}",
     "output": f"The performance might be: {MOTION_HOLDER}"},
    {"input": f"Here’s a music track: {MUSIC_HOLDER}. What movements might you create?",
     "output": f"You might create movements like this: {MOTION_HOLDER}"},
    {"input": f"Play this music: {MUSIC_HOLDER}. How should you dance to it?",
     "output": f"You might dance like this: {MOTION_HOLDER}"},
    {"input": f"Match a dance to the sound: {MUSIC_HOLDER}",
     "output": f"The matched dance looks like: {MOTION_HOLDER}"},
    {"input": f"Listen to the music: {MUSIC_HOLDER}. What movements fit?",
     "output": f"The movements that fit are: {MOTION_HOLDER}"},
    {"input": f"What type of dance would you perform to this song? {MUSIC_HOLDER}",
     "output": f"The performance would look like: {MOTION_HOLDER}"},
    {"input": f"Can you generate a dance based on this music? {MUSIC_HOLDER}",
     "output": f"Yes, here is the generated dance: {MOTION_HOLDER}"},
    {"input": f"Create dance steps to this track: {MUSIC_HOLDER}",
     "output": f"The dance steps would be: {MOTION_HOLDER}"},
    {"input": f"This is a song: {MUSIC_HOLDER}. How might the dancer move?",
     "output": f"The dancer might move like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this music: {MUSIC_HOLDER}. What dance movements would you perform?",
     "output": f"You might perform movements like this: {MOTION_HOLDER}"},
    {"input": f"Imagine a dance for this music: {MUSIC_HOLDER}",
     "output": f"The imagined dance looks like: {MOTION_HOLDER}"},
    {"input": f"Here’s an audio track: {MUSIC_HOLDER}. What dance choreography could fit?",
     "output": f"The choreography could look like: {MOTION_HOLDER}"},
    {"input": f"How would you choreograph a dance to this song? {MUSIC_HOLDER}",
     "output": f"The choreography might be: {MOTION_HOLDER}"},
    {"input": f"Show dance steps for this tune: {MUSIC_HOLDER}", "output": f"The steps would be: {MOTION_HOLDER}"},
    {"input": f"Play the music and show a dance: {MUSIC_HOLDER}",
     "output": f"The dance would look like: {MOTION_HOLDER}"},
    {"input": f"Generate movements to match this sound: {MUSIC_HOLDER}",
     "output": f"The matching movements are: {MOTION_HOLDER}"},
    {"input": f"This song sounds like: {MUSIC_HOLDER}. How would you dance to it?",
     "output": f"The dance might look like: {MOTION_HOLDER}"},
    {"input": f"Listen to this melody: {MUSIC_HOLDER}. What dance fits this song?",
     "output": f"The dance might fit like: {MOTION_HOLDER}"},
    {"input": f"Can you generate a dance routine for this song? {MUSIC_HOLDER}",
     "output": f"The routine might be like: {MOTION_HOLDER}"},
    {"input": f"Play this music and show a dance sequence: {MUSIC_HOLDER}",
     "output": f"The sequence might be: {MOTION_HOLDER}"},
    {"input": f"What kind of choreography would you create for this music? {MUSIC_HOLDER}",
     "output": f"The choreography might be: {MOTION_HOLDER}"},
    {"input": f"This is the music: {MUSIC_HOLDER}. Create a matching dance.",
     "output": f"The matching dance could be: {MOTION_HOLDER}"},
    {"input": f"What dance moves would go with this sound? {MUSIC_HOLDER}",
     "output": f"The moves might look like: {MOTION_HOLDER}"},
    {"input": f"Show the dance that matches this track: {MUSIC_HOLDER}",
     "output": f"The matching dance is: {MOTION_HOLDER}"},
    {"input": f"Listen to this song and show a performance: {MUSIC_HOLDER}",
     "output": f"The performance would be: {MOTION_HOLDER}"},
    {"input": f"Play this tune: {MUSIC_HOLDER}. What choreography fits?",
     "output": f"The choreography fits like: {MOTION_HOLDER}"},
    {"input": f"How might a dancer perform to this song? {MUSIC_HOLDER}",
     "output": f"They might perform like this: {MOTION_HOLDER}"},
    {"input": f"Listen to the music and create a dance set: {MUSIC_HOLDER}",
     "output": f"The dance set looks like: {MOTION_HOLDER}"},
    {"input": f"Generate a dance to fit this track: {MUSIC_HOLDER}", "output": f"The dance fits like: {MOTION_HOLDER}"},
    {"input": f"Listen to this audio and think of dance steps: {MUSIC_HOLDER}",
     "output": f"The steps might be: {MOTION_HOLDER}"},
    {"input": f"Here is the music: {MUSIC_HOLDER}. How would you move?",
     "output": f"The movement might be like: {MOTION_HOLDER}"},
    {"input": f"Can you create a dance set for this tune? {MUSIC_HOLDER}",
     "output": f"The dance set could be like: {MOTION_HOLDER}"},
    {"input": f"This song is playing: {MUSIC_HOLDER}. How might the dancer move?",
     "output": f"The dancer might move like this: {MOTION_HOLDER}"},
    {"input": f"Here’s the audio track: {MUSIC_HOLDER}. Show the matching movements.",
     "output": f"The movements might be: {MOTION_HOLDER}"}
]
