from mmotion.utils.task.modality import DURATION_HOLDER, MOTION_HOLDER

L2M_TEMPLATE = [
    {'input': f"Make a motion, which is about {DURATION_HOLDER} seconds.",
     'output': f"Okay, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion lasting around {DURATION_HOLDER} seconds.",
     'output': f"Sure, here's a motion that lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion approximately {DURATION_HOLDER} seconds long.",
     'output': f"Alright, this motion is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce a motion sequence that takes about {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion sequence takes about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Can you make a motion for around {DURATION_HOLDER} seconds?",
     'output': f"Yes, here is a motion lasting around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Please create a motion sequence lasting {DURATION_HOLDER} seconds.",
     'output': f"Here you go, a motion sequence that lasts {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion that is about {DURATION_HOLDER} seconds long.",
     'output': f"Okay, here's a motion about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Construct a motion sequence that lasts approximately {DURATION_HOLDER} seconds.",
     'output': f"This motion sequence lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion of about {DURATION_HOLDER} seconds.",
     'output': f"Sure thing, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion lasting around {DURATION_HOLDER} seconds.",
     'output': f"Here is a motion that lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a sequence of actions for about {DURATION_HOLDER} seconds.",
     'output': f"Okay, this sequence of actions is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion sequence lasting about {DURATION_HOLDER} seconds.",
     'output': f"Sure, this motion sequence lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion that lasts {DURATION_HOLDER} seconds.",
     'output': f"Alright, here is a motion that lasts {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion approximately {DURATION_HOLDER} seconds in length.",
     'output': f"This motion is approximately {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Design a sequence of actions lasting {DURATION_HOLDER} seconds.",
     'output': f"Here is a sequence of actions lasting {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion around {DURATION_HOLDER} seconds long.",
     'output': f"Okay, this motion is around {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a motion sequence about {DURATION_HOLDER} seconds in duration.",
     'output': f"Got it, this motion sequence is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion sequence of {DURATION_HOLDER} seconds.",
     'output': f"Yes, this motion sequence is {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion approximately lasting {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a sequence that is about {DURATION_HOLDER} seconds long.",
     'output': f"Sure, here is a sequence about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion that lasts around {DURATION_HOLDER} seconds.",
     'output': f"This motion lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion for approximately {DURATION_HOLDER} seconds.",
     'output': f"Okay, here is a motion for approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce an action sequence lasting {DURATION_HOLDER} seconds.",
     'output': f"Got it, this action sequence lasts {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion of about {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion approximately {DURATION_HOLDER} seconds long.",
     'output': f"Sure, this motion is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion sequence lasting around {DURATION_HOLDER} seconds.",
     'output': f"Here is a motion sequence lasting around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion sequence about {DURATION_HOLDER} seconds in duration.",
     'output': f"Yes, this motion sequence is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion that is about {DURATION_HOLDER} seconds long.",
     'output': f"This motion is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a motion lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a sequence lasting about {DURATION_HOLDER} seconds.",
     'output': f"Alright, here is a sequence lasting about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate an action sequence of around {DURATION_HOLDER} seconds.",
     'output': f"Okay, this action sequence is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion sequence that takes {DURATION_HOLDER} seconds.",
     'output': f"Sure, this motion sequence takes {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Construct a motion that is about {DURATION_HOLDER} seconds long.",
     'output': f"This motion is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a sequence lasting around {DURATION_HOLDER} seconds.",
     'output': f"Alright, here is a sequence lasting around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion sequence lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion of about {DURATION_HOLDER} seconds.",
     'output': f"Okay, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion sequence that lasts around {DURATION_HOLDER} seconds.",
     'output': f"Yes, this motion sequence lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion approximately {DURATION_HOLDER} seconds in length.",
     'output': f"Sure, this motion is approximately {DURATION_HOLDER} seconds in length. {MOTION_HOLDER}"},
    {'input': f"Design a sequence of actions about {DURATION_HOLDER} seconds long.",
     'output': f"This sequence of actions is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a motion that lasts {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion lasts {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence around {DURATION_HOLDER} seconds long.",
     'output': f"Okay, here is a motion sequence around {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Construct an action sequence of approximately {DURATION_HOLDER} seconds.",
     'output': f"This action sequence is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion approximately {DURATION_HOLDER} seconds in duration.",
     'output': f"Sure, this motion is approximately {DURATION_HOLDER} seconds in duration. {MOTION_HOLDER}"},
    {'input': f"Create a motion sequence lasting around {DURATION_HOLDER} seconds.",
     'output': f"Alright, here is a motion sequence lasting around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a sequence that is about {DURATION_HOLDER} seconds long.",
     'output': f"This sequence is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a motion lasting about {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a motion of around {DURATION_HOLDER} seconds.",
     'output': f"Okay, this motion is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a sequence lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"This sequence lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create an action sequence lasting about {DURATION_HOLDER} seconds.",
     'output': f"Sure, this action sequence lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion that takes {DURATION_HOLDER} seconds.",
     'output': f"Alright, here is a motion that takes {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion sequence of approximately {DURATION_HOLDER} seconds.",
     'output': f"This motion sequence is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce an action lasting around {DURATION_HOLDER} seconds.",
     'output': f"Okay, this action lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a sequence of about {DURATION_HOLDER} seconds.",
     'output': f"Sure, this sequence is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Construct a motion that lasts approximately {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a sequence lasting around {DURATION_HOLDER} seconds.",
     'output': f"This sequence lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion of about {DURATION_HOLDER} seconds in duration.",
     'output': f"Got it, this motion is about {DURATION_HOLDER} seconds in duration. {MOTION_HOLDER}"},
    {'input': f"Develop a sequence approximately {DURATION_HOLDER} seconds long.",
     'output': f"This sequence is approximately {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence that lasts about {DURATION_HOLDER} seconds.",
     'output': f"Sure, this motion sequence lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design an action sequence of around {DURATION_HOLDER} seconds.",
     'output': f"Okay, this action sequence is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce a motion sequence lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion sequence lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion that is about {DURATION_HOLDER} seconds in length.",
     'output': f"Got it, this motion is about {DURATION_HOLDER} seconds in length. {MOTION_HOLDER}"},
    {'input': f"Generate a sequence that lasts around {DURATION_HOLDER} seconds.",
     'output': f"This sequence lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion of about {DURATION_HOLDER} seconds.",
     'output': f"Sure, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create an action that lasts approximately {DURATION_HOLDER} seconds.",
     'output': f"Alright, this action lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a motion sequence of around {DURATION_HOLDER} seconds.",
     'output': f"This motion sequence is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion lasting about {DURATION_HOLDER} seconds.",
     'output': f"Okay, here is a motion lasting about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce an action sequence of approximately {DURATION_HOLDER} seconds.",
     'output': f"Got it, this action sequence is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a sequence of actions about {DURATION_HOLDER} seconds long.",
     'output': f"Sure, this sequence of actions is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Generate a motion lasting around {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Construct a motion sequence of approximately {DURATION_HOLDER} seconds.",
     'output': f"This motion sequence is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion sequence lasting about {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion sequence lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop an action sequence of around {DURATION_HOLDER} seconds.",
     'output': f"Sure, this action sequence is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce a motion lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a sequence lasting around {DURATION_HOLDER} seconds.",
     'output': f"This sequence lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a motion of about {DURATION_HOLDER} seconds.",
     'output': f"Okay, this motion is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate a motion sequence of approximately {DURATION_HOLDER} seconds.",
     'output': f"Sure, this motion sequence is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion that lasts around {DURATION_HOLDER} seconds.",
     'output': f"Got it, this motion lasts around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Develop a sequence that is about {DURATION_HOLDER} seconds long.",
     'output': f"This sequence is about {DURATION_HOLDER} seconds long. {MOTION_HOLDER}"},
    {'input': f"Produce a motion sequence lasting about {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion sequence lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Make a motion of around {DURATION_HOLDER} seconds in duration.",
     'output': f"Sure, this motion is around {DURATION_HOLDER} seconds in duration. {MOTION_HOLDER}"},
    {'input': f"Generate an action lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Okay, this action lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Design a sequence of about {DURATION_HOLDER} seconds.",
     'output': f"Got it, this sequence is about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion approximately lasting {DURATION_HOLDER} seconds.",
     'output': f"Alright, this motion is approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Formulate an action sequence of around {DURATION_HOLDER} seconds.",
     'output': f"Sure, this action sequence is around {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Produce a motion that lasts about {DURATION_HOLDER} seconds.",
     'output': f"Okay, this motion lasts about {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Generate a sequence lasting approximately {DURATION_HOLDER} seconds.",
     'output': f"Alright, this sequence lasts approximately {DURATION_HOLDER} seconds. {MOTION_HOLDER}"},
    {'input': f"Create a motion of about {DURATION_HOLDER} seconds in length.",
     'output': f"Sure, this motion is about {DURATION_HOLDER} seconds in length. {MOTION_HOLDER}"},
]