"""
    For motion-to-text task in humanml3d
"""
from mmotion.utils.task.modality import MOTION_HOLDER, CAPTION_HOLDER

M2T_TEMPLATE = [
    {'input': f"Describe this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Here is a motion sequence: {MOTION_HOLDER}, what's the man doing?", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Do you know what's he doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this person doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this action: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this motion show? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you tell what's going on? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the action here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the action: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you tell me what this action is? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Please describe this action: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What activity is shown here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what's happening: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what you see: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's shown in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this motion sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's going on in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is happening in this sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe what's happening? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what this person is doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's this action sequence about? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe this action sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this man doing in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what's happening here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this activity: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is the person doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe the action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what this person is doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is being shown here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what this action is: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe this activity: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What motion is this? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this action depict? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person in the motion doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is shown here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What activity is this? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what this motion shows: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe this sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the sequence here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is depicted in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you tell me what this is? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this scene: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this motion sequence about? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what this person is doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what's going on here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is taking place here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's he doing in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe this motion sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this motion depict? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what is happening here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the action in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the activity: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this person doing in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what this person is doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the activity shown here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what you see here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is this? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you explain this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's going on in this sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what is being shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what this motion is: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this person do in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what this is: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what this action is: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is this person performing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what's this person doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the action depicted here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe this motion for me? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this motion showing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what happens in this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what this motion is about: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what's going on in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's this person doing here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what action is this: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is shown in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's he doing in this sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the action: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this motion show? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in this action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you tell what this is? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe this scene: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is shown here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what is shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this motion sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's shown in this sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe this action for me? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in this scene? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what this motion shows: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What activity is being shown? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what action is shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this activity? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what you see: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the activity shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person in this motion doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the action taking place: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is happening here? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in the sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what is happening: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the person’s action: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What does this motion show? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the action shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain this motion sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening in the sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the motion sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is the person doing in the action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe what's shown? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the activity depicted? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is shown in this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what's happening: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this action sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what's happening in the sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Can you describe the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the action being performed? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the sequence shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person in the action doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the activity: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion sequence shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in the motion sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the motion shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what action is taking place: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person shown doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the activity taking place: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what the person is doing: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the action depicted: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the activity in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what's taking place here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what happens in this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is taking place: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in this sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what's happening in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the person’s activity: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What action is the person performing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what you see in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this motion sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what action is being shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the person’s action in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person doing in this activity? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what this activity is: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this action sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the action sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is taking place here: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the person shown in the motion doing? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the action taking place: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the person’s activity shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's this person doing in the sequence? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what’s happening in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain what’s going on: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the sequence shown in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's the activity shown in this motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what action is happening: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this scene? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the motion shown in the sequence: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what action is depicted: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What is this person doing in the action? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Tell me what’s happening in the motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe the motion that is shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What's happening in this sequence of actions? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Explain the activity shown: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"Describe what is happening in this motion: {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
    {'input': f"What’s the activity depicted in the motion? {MOTION_HOLDER}", 'output': f"{CAPTION_HOLDER}"},
]
