"""
    randomly sample a motion caption
"""
from mmotion.utils.task.modality import CAPTION_HOLDER

N2T_TEMPLATE = [
    {'input': 'Randomly describe a motion', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': "Generate a random action description.", 'output': f"Okay, there is an action description: {CAPTION_HOLDER}"},
    {'input': 'Describe a random action.', 'output': f"Got it, here's what I came up with: {CAPTION_HOLDER}"},
    {'input': 'Can you randomly generate an action description?', 'output': f"Of course, here you go: {CAPTION_HOLDER}"},
    {'input': 'Give me a random action description.', 'output': f"Alright, here's one: {CAPTION_HOLDER}"},
    {'input': 'Randomly generate an action for me.', 'output': f"Sure thing, here it is: {CAPTION_HOLDER}"},
    {'input': 'Describe an action at random.', 'output': f"No problem, here you go: {CAPTION_HOLDER}"},
    {'input': 'Can you give me a random description of a motion?', 'output': f"Absolutely, here's one: {CAPTION_HOLDER}"},
    {'input': 'Please create a random action description.', 'output': f"Alright, here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate an action description randomly.', 'output': f"Okay, take a look: {CAPTION_HOLDER}"},
    {'input': 'Give me a random action detail.', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'What is a random action?', 'output': f"Here's an example: {CAPTION_HOLDER}"},
    {'input': 'Create a random description of a motion.', 'output': f"Here you go: {CAPTION_HOLDER}"},
    {'input': 'Provide a random action description.', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Describe any random motion.', 'output': f"Here's one for you: {CAPTION_HOLDER}"},
    {'input': 'Randomly create an action description.', 'output': f"Alright, check this out: {CAPTION_HOLDER}"},
    {'input': 'Tell me a random action.', 'output': f"Sure, here's one: {CAPTION_HOLDER}"},
    {'input': 'Describe a motion randomly.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate a description for a random action.', 'output': f"Okay, here you go: {CAPTION_HOLDER}"},
    {'input': 'What is a random description of an action?', 'output': f"Here's an action: {CAPTION_HOLDER}"},
    {'input': 'Please describe a random action.', 'output': f"Of course, here it is: {CAPTION_HOLDER}"},
    {'input': 'Can you generate a random action description for me?', 'output': f"Absolutely, here you are: {CAPTION_HOLDER}"},
    {'input': 'Give me any random action description.', 'output': f"Here you go: {CAPTION_HOLDER}"},
    {'input': 'Provide a description of a random action.', 'output': f"Alright, here's one: {CAPTION_HOLDER}"},
    {'input': 'Create a random motion description.', 'output': f"Got it, here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate an arbitrary action description.', 'output': f"Okay, here's what I have: {CAPTION_HOLDER}"},
    {'input': 'Can you describe a random action?', 'output': f"Sure, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Give me a randomly generated action.', 'output': f"Alright, take a look: {CAPTION_HOLDER}"},
    {'input': 'Describe a random action for me.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate a random action explanation.', 'output': f"Absolutely, here you go: {CAPTION_HOLDER}"},
    {'input': 'What is a random action description?', 'output': f"Here's one: {CAPTION_HOLDER}"},
    {'input': 'Randomly provide an action description.', 'output': f"Sure thing, here it is: {CAPTION_HOLDER}"},
    {'input': 'Create any random action description.', 'output': f"Here you go: {CAPTION_HOLDER}"},
    {'input': 'Please generate a random motion description.', 'output': f"Okay, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Give me a description of a random motion.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Describe a random action in detail.', 'output': f"Sure, here's one: {CAPTION_HOLDER}"},
    {'input': 'Generate a random action text.', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'What is a random description of motion?', 'output': f"Here's an example: {CAPTION_HOLDER}"},
    {'input': 'Please describe any random action.', 'output': f"Alright, here it is: {CAPTION_HOLDER}"},
    {'input': 'Can you create a random action description for me?', 'output': f"Absolutely, here you go: {CAPTION_HOLDER}"},
    {'input': 'Give me any description of a random action.', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Provide a randomly generated action description.', 'output': f"Okay, here you are: {CAPTION_HOLDER}"},
    {'input': 'Create a description for any random action.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate a motion description at random.', 'output': f"Alright, here you go: {CAPTION_HOLDER}"},
    {'input': 'Can you randomly describe an action for me?', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Give me a random action description, please.', 'output': f"Okay, here you go: {CAPTION_HOLDER}"},
    {'input': 'Describe any action randomly.', 'output': f"Sure, here's one: {CAPTION_HOLDER}"},
    {'input': 'Randomly generate a description of a motion.', 'output': f"Alright, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Tell me a random description of an action.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Describe an action at random for me.', 'output': f"Okay, here you go: {CAPTION_HOLDER}"},
    {'input': 'Generate any random action description.', 'output': f"Sure, here's one: {CAPTION_HOLDER}"},
    {'input': 'What is the description of a random action?', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'Please randomly describe a motion.', 'output': f"Alright, here it is: {CAPTION_HOLDER}"},
    {'input': 'Can you create an action description randomly?', 'output': f"Absolutely, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Give me a random motion description.', 'output': f"Sure, here you go: {CAPTION_HOLDER}"},
    {'input': 'Provide any random action description.', 'output': f"Okay, here it is: {CAPTION_HOLDER}"},
    {'input': 'Create a random action text.', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'Generate an action description randomly for me.', 'output': f"Sure thing, here it is: {CAPTION_HOLDER}"},
    {'input': 'What is a random motion description?', 'output': f"Alright, here's one: {CAPTION_HOLDER}"},
    {'input': 'Please describe a randomly generated action.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Can you describe any random action for me?', 'output': f"Sure, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Give me a description of a randomly generated action.', 'output': f"Okay, here you go: {CAPTION_HOLDER}"},
    {'input': 'Provide a description of any random action.', 'output': f"Absolutely, here it is: {CAPTION_HOLDER}"},
    {'input': 'Create a random description of an action.', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'Generate a description of a random motion.', 'output': f"Alright, here's one: {CAPTION_HOLDER}"},
    {'input': 'Can you randomly create an action description?', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Give me any randomly generated action description.', 'output': f"Okay, here you go: {CAPTION_HOLDER}"},
    {'input': 'Describe a randomly generated action.', 'output': f"Sure, here's one: {CAPTION_HOLDER}"},
    {'input': 'Randomly generate an action text.', 'output': f"Alright, here's an example: {CAPTION_HOLDER}"},
    {'input': 'What is a randomly generated description of an action?', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'Please provide a random action description.', 'output': f"Okay, here it is: {CAPTION_HOLDER}"},
    {'input': 'Can you generate a description of a random action for me?', 'output': f"Sure thing, here it is: {CAPTION_HOLDER}"},
    {'input': 'Give me a randomly created action description.', 'output': f"Alright, here you go: {CAPTION_HOLDER}"},
    {'input': 'Describe any random action text.', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Create a description for a random motion.', 'output': f"Okay, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Generate a random motion description for me.', 'output': f"Alright, here you go: {CAPTION_HOLDER}"},
    {'input': 'What is a randomly generated motion description?', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Please describe any randomly generated action.', 'output': f"Absolutely, here's one: {CAPTION_HOLDER}"},
    {'input': 'Can you create a randomly generated action description for me?', 'output': f"Sure, here you go: {CAPTION_HOLDER}"},
    {'input': 'Give me any randomly generated action description, please.', 'output': f"Alright, here it is: {CAPTION_HOLDER}"},
    {'input': 'Provide a random description of an action.', 'output': f"Okay, here's one: {CAPTION_HOLDER}"},
    {'input': 'Create a text description for a random action.', 'output': f"Sure, here it is: {CAPTION_HOLDER}"},
    {'input': 'Generate a random description of an action.', 'output': f"Here you are: {CAPTION_HOLDER}"},
    {'input': 'Can you describe any randomly generated motion?', 'output': f"Alright, here's one: {CAPTION_HOLDER}"},
    {'input': 'Give me a random description of an action.', 'output': f"Sure, here you go: {CAPTION_HOLDER}"},
    {'input': 'Describe any randomly generated action text.', 'output': f"Here it is: {CAPTION_HOLDER}"},
    {'input': 'Create a description of any random action.', 'output': f"Alright, here's an example: {CAPTION_HOLDER}"},
    {'input': 'Generate a motion description randomly for me.', 'output': f"Okay, here it is: {CAPTION_HOLDER}"},
]
