"""
For humanml3d,
Randomly generate a motion and its corresponding caption
"""
from mmotion.utils.task.modality import CAPTION_HOLDER, MOTION_HOLDER


N2TM_TEMPLATE = [
    {'input': f"Imagine a motion, show and describe it.", 'output': f"I imagined such a motion: {CAPTION_HOLDER} Which shows as below: {MOTION_HOLDER}"},
    {'input': f"Think of a motion, illustrate it and explain.", 'output': f"Here's the motion I thought of: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Visualize a motion, then describe and display it.", 'output': f"This is the motion I visualized: {CAPTION_HOLDER}. It appears like this: {MOTION_HOLDER}"},
    {'input': f"Create a motion in your mind, show it and explain.", 'output': f"I created this motion: {CAPTION_HOLDER} And it looks as follows: {MOTION_HOLDER}"},
    {'input': f"Invent a motion, describe it and display it.", 'output': f"This is the motion I invented: {CAPTION_HOLDER} And here is how it shows: {MOTION_HOLDER}"},
    {'input': f"Envision a motion, show it and describe.", 'output': f"The motion I envisioned is: {CAPTION_HOLDER} Shown as: {MOTION_HOLDER}"},
    {'input': f"Come up with a motion, illustrate and describe it.", 'output': f"I came up with this motion: {CAPTION_HOLDER}. It appears like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a random motion, show and explain it.", 'output': f"I imagined this random motion: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Think of a random motion, describe and display it.", 'output': f"The random motion I thought of is: {CAPTION_HOLDER} Ahown here: {MOTION_HOLDER}"},
    {'input': f"Create a mental image of a motion, show and describe it.", 'output': f"I created a mental image of this motion: {CAPTION_HOLDER} And it looks as follows: {MOTION_HOLDER}"},
    {'input': f"Invent a random motion, display and describe it.", 'output': f"This random motion I invented is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Visualize a random motion, show and explain it.", 'output': f"The random motion I visualized is: {CAPTION_HOLDER} Appearing like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a movement, show it and describe.", 'output': f"I imagined this movement: {CAPTION_HOLDER} And it is shown like this: {MOTION_HOLDER}"},
    {'input': f"Think of an action, illustrate and explain.", 'output': f"This is the action I thought of: {CAPTION_HOLDER} And it appears as follows: {MOTION_HOLDER}"},
    {'input': f"Envision a movement, describe and display it.", 'output': f"The movement I envisioned is: {CAPTION_HOLDER} Ahown here: {MOTION_HOLDER}"},
    {'input': f"Create an action in your mind, show and explain.", 'output': f"I created this action in my mind: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Come up with a movement, display and describe it.", 'output': f"The movement I came up with is: {CAPTION_HOLDER} And it is shown as: {MOTION_HOLDER}"},
    {'input': f"Visualize an action, show and describe it.", 'output': f"I visualized this action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a random movement, show and explain.", 'output': f"This random movement I imagined is: {CAPTION_HOLDER} And it is shown as follows: {MOTION_HOLDER}"},
    {'input': f"Think of a random movement, illustrate and describe it.", 'output': f"The random movement I thought of is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Create a mental image of an action, display and describe it.", 'output': f"I created a mental image of this action: {CAPTION_HOLDER} And it is shown as: {MOTION_HOLDER}"},
    {'input': f"Invent a random movement, show and describe it.", 'output': f"The random movement I invented is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Visualize a random action, describe and display it.", 'output': f"This random action I visualized is: {CAPTION_HOLDER} Ahown here: {MOTION_HOLDER}"},
    {'input': f"Imagine an arbitrary motion, show and explain it.", 'output': f"I imagined this arbitrary motion: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Think of an arbitrary motion, illustrate and describe.", 'output': f"The arbitrary motion I thought of is: {CAPTION_HOLDER} Ahown as follows: {MOTION_HOLDER}"},
    {'input': f"Envision an arbitrary action, display and describe it.", 'output': f"The arbitrary action I envisioned is: {CAPTION_HOLDER} And it is shown as: {MOTION_HOLDER}"},
    {'input': f"Create an arbitrary motion in your mind, show and explain it.", 'output': f"I created this arbitrary motion: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Invent an arbitrary action, describe and display it.", 'output': f"The arbitrary action I invented is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Visualize an arbitrary movement, show and describe it.", 'output': f"This arbitrary movement I visualized is: {CAPTION_HOLDER} And it is shown like this: {MOTION_HOLDER}"},
    {'input': f"Imagine any motion, show and describe it.", 'output': f"I imagined this motion: {CAPTION_HOLDER} And it appears as: {MOTION_HOLDER}"},
    {'input': f"Think of any action, illustrate and describe it.", 'output': f"The action I thought of is: {CAPTION_HOLDER} And it is shown here: {MOTION_HOLDER}"},
    {'input': f"Envision any movement, display and explain it.", 'output': f"The movement I envisioned is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Create any motion in your mind, show and describe it.", 'output': f"I created this motion: {CAPTION_HOLDER} And it is shown like this: {MOTION_HOLDER}"},
    {'input': f"Invent any action, describe and display it.", 'output': f"The action I invented is: {CAPTION_HOLDER} And it appears as follows: {MOTION_HOLDER}"},
    {'input': f"Visualize any movement, show and describe it.", 'output': f"This movement I visualized is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a motion, show and describe it.", 'output': f"I imagined this motion: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Think of a motion, illustrate and explain it.", 'output': f"The motion I thought of is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Envision a motion, show it and describe.", 'output': f"I envisioned this motion: {CAPTION_HOLDER} And it looks as follows: {MOTION_HOLDER}"},
    {'input': f"Create a motion in your mind, show and explain.", 'output': f"The motion I created is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Invent a motion, display and describe it.", 'output': f"I invented this motion: {CAPTION_HOLDER} And it appears as: {MOTION_HOLDER}"},
    {'input': f"Visualize a motion, show it and describe.", 'output': f"The motion I visualized is: {CAPTION_HOLDER} And it is shown here: {MOTION_HOLDER}"},
    {'input': f"Imagine an action, show and describe it.", 'output': f"This is the action I imagined: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Think of an action, illustrate it and explain.", 'output': f"The action I thought of is: {CAPTION_HOLDER} And it is shown as follows: {MOTION_HOLDER}"},
    {'input': f"Envision an action, show it and describe.", 'output': f"I envisioned this action: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Create an action in your mind, show and explain.", 'output': f"This action I created is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Invent an action, display and describe it.", 'output': f"The action I invented is: {CAPTION_HOLDER} And it is shown here: {MOTION_HOLDER}"},
    {'input': f"Visualize an action, show it and describe.", 'output': f"I visualized this action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a movement, show and describe it.", 'output': f"This is the movement I imagined: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Think of a movement, illustrate it and explain.", 'output': f"The movement I thought of is: {CAPTION_HOLDER} And it is shown as follows: {MOTION_HOLDER}"},
    {'input': f"Envision a movement, show it and describe.", 'output': f"I envisioned this movement: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Create a movement in your mind, show and explain.", 'output': f"This movement I created is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Invent a movement, display and describe it.", 'output': f"The movement I invented is: {CAPTION_HOLDER} And it is shown here: {MOTION_HOLDER}"},
    {'input': f"Visualize a movement, show it and describe.", 'output': f"I visualized this movement: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a random action, show and describe it.", 'output': f"This is the random action I imagined: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Think of a random action, illustrate and explain it.", 'output': f"The random action I thought of is: {CAPTION_HOLDER} And it is shown as: {MOTION_HOLDER}"},
    {'input': f"Envision a random action, show it and describe.", 'output': f"I envisioned this random action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Create a random action in your mind, show and explain it.", 'output': f"This random action I created is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Invent a random action, display and describe it.", 'output': f"The random action I invented is: {CAPTION_HOLDER} And it is shown here: {MOTION_HOLDER}"},
    {'input': f"Visualize a random action, show it and describe.", 'output': f"I visualized this random action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine a random movement, show and describe it.", 'output': f"This is the random movement I imagined: {CAPTION_HOLDER} And it is shown like this: {MOTION_HOLDER}"},
    {'input': f"Think of a random movement, illustrate and explain it.", 'output': f"The random movement I thought of is: {CAPTION_HOLDER} And it appears as follows: {MOTION_HOLDER}"},
    {'input': f"Envision a random movement, show it and describe.", 'output': f"I envisioned this random movement: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Create a random movement in your mind, show and explain it.", 'output': f"This random movement I created is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Invent a random movement, display and describe it.", 'output': f"The random movement I invented is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Visualize a random movement, show it and describe.", 'output': f"I visualized this random movement: {CAPTION_HOLDER} And it is shown as follows: {MOTION_HOLDER}"},
    {'input': f"Imagine an arbitrary action, show and describe it.", 'output': f"This is the arbitrary action I imagined: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Think of an arbitrary action, illustrate and explain.", 'output': f"The arbitrary action I thought of is: {CAPTION_HOLDER} And it appears as: {MOTION_HOLDER}"},
    {'input': f"Envision an arbitrary action, show it and describe.", 'output': f"I envisioned this arbitrary action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Create an arbitrary action in your mind, show and explain it.", 'output': f"This arbitrary action I created is: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Invent an arbitrary action, display and describe it.", 'output': f"The arbitrary action I invented is: {CAPTION_HOLDER} And it is shown as: {MOTION_HOLDER}"},
    {'input': f"Visualize an arbitrary action, show it and describe.", 'output': f"I visualized this arbitrary action: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Imagine an arbitrary movement, show and describe it.", 'output': f"This is the arbitrary movement I imagined: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
    {'input': f"Think of an arbitrary movement, illustrate and explain it.", 'output': f"The arbitrary movement I thought of is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Envision an arbitrary movement, show it and describe.", 'output': f"I envisioned this arbitrary movement: {CAPTION_HOLDER} And it appears as follows: {MOTION_HOLDER}"},
    {'input': f"Create an arbitrary movement in your mind, show and explain it.", 'output': f"This arbitrary movement I created is: {CAPTION_HOLDER} And it is shown like this: {MOTION_HOLDER}"},
    {'input': f"Invent an arbitrary movement, display and describe it.", 'output': f"The arbitrary movement I invented is: {CAPTION_HOLDER} And it looks like this: {MOTION_HOLDER}"},
    {'input': f"Visualize an arbitrary movement, show it and describe.", 'output': f"I visualized this arbitrary movement: {CAPTION_HOLDER} And it appears like this: {MOTION_HOLDER}"},
]
