from mmotion.utils.task.modality import CAPTION_HOLDER, MOTION_HOLDER

T2M_TEMPLATE = [
    {'input': f"Generate a sequence of actions based on my description: {CAPTION_HOLDER}", 'output': f"A possible motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize this motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is a motion sequence corresponding to your caption. {MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Can you show a motion for this caption: {CAPTION_HOLDER}?", 'output': f"Here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Based on my description, generate an action sequence: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Show me a motion sequence for this description: {CAPTION_HOLDER}", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize the motion described here: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Generate actions according to my description: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Create a motion sequence from this caption: {CAPTION_HOLDER}", 'output': f"Here is the generated sequence: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion based on my caption: {CAPTION_HOLDER}?", 'output': f"This is the corresponding motion sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions from this description: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence from this description: {CAPTION_HOLDER}", 'output': f"Okay, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize the following action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Based on my caption, create a motion sequence: {CAPTION_HOLDER}", 'output': f"The generated sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions for this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this action: {CAPTION_HOLDER}?", 'output': f"Sure, here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Create actions based on this description: {CAPTION_HOLDER}", 'output': f"Here is the motion: {MOTION_HOLDER}"},
    {'input': f"Generate a sequence based on my description: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize this sequence for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a motion from my description: {CAPTION_HOLDER}", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Can you show a sequence of actions based on this caption: {CAPTION_HOLDER}?", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Based on this description, generate a sequence of actions: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion for this caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Create actions from my description: {CAPTION_HOLDER}", 'output': f"The resulting sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize this motion described here: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Generate actions according to this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion based on this description: {CAPTION_HOLDER}?", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions from my description: {CAPTION_HOLDER}", 'output': f"The resulting sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion from my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize the following motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions from this caption: {CAPTION_HOLDER}", 'output': f"The generated sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion for this description: {CAPTION_HOLDER}", 'output': f"Here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the action described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from my description: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions from this description: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Visualize this action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Create a motion sequence from this description: {CAPTION_HOLDER}", 'output': f"Here is the resulting sequence: {MOTION_HOLDER}"},
    {'input': f"Can you generate actions based on my description: {CAPTION_HOLDER}?", 'output': f"This is the corresponding motion: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions for this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on this description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Visualize the action described here: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions from this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions based on this description: {CAPTION_HOLDER}", 'output': f"Here is the sequence: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion is: {MOTION_HOLDER}"},
    {'input': f"Generate actions based on my description: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion from this description: {CAPTION_HOLDER}?", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions according to this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence from this caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize the following action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Based on this description, create a motion sequence: {CAPTION_HOLDER}", 'output': f"The generated sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this caption: {CAPTION_HOLDER}?", 'output': f"Sure, here is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Create actions from the description: {CAPTION_HOLDER}", 'output': f"Here is the motion: {MOTION_HOLDER}"},
    {'input': f"Generate a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize this motion: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a motion based on the description: {CAPTION_HOLDER}", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Can you show a sequence of actions for this caption: {CAPTION_HOLDER}?", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Based on this description, generate actions: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence from my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Create actions from this description: {CAPTION_HOLDER}", 'output': f"The resulting sequence is: {MOTION_HOLDER}"},
    {'input': f"Visualize the action described: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Generate actions based on this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from my caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion for this description: {CAPTION_HOLDER}?", 'output': f"This is the motion: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions from this caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on this caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this described motion: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from the description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion from the caption: {CAPTION_HOLDER}?", 'output': f"This is the motion: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions for this description: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize the described action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions from this description: {CAPTION_HOLDER}", 'output': f"The generated motion is: {MOTION_HOLDER}"},
    {'input': f"Show me a motion described here: {CAPTION_HOLDER}", 'output': f"Here is the motion: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the action described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the caption: {CAPTION_HOLDER}", 'output': f"The motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for this caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this description: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize the described motion: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions from this description: {CAPTION_HOLDER}", 'output': f"The generated motion is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this action described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions based on the caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions from the caption: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions from the caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this description: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion based on the description: {CAPTION_HOLDER}?", 'output': f"This is the motion sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this action described here for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on this description: {CAPTION_HOLDER}", 'output': f"The generated sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions based on the description: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this description: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on this description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize the described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on my caption: {CAPTION_HOLDER}", 'output': f"The generated motion is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this described caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on my description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence from the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on the description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence from the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this action described here: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions from this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions based on the caption: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the described motion: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this description: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence from this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence based on the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated motion is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this described caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on my description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on my description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this description: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for this caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the described action: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence from the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this described caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on my description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the described action: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this description: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this described caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on my description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this described caption: {CAPTION_HOLDER}", 'output': f"The motion sequence generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on my description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the description: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the caption: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the description: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize this motion described here: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from the described caption: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this description: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my description: {CAPTION_HOLDER}", 'output': f"Okay, here it is: {MOTION_HOLDER}"},
    {'input': f"Visualize this described motion for me: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create actions based on the caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me a sequence of actions described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the described action: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate actions from this description: {CAPTION_HOLDER}", 'output': f"The motion generated is: {MOTION_HOLDER}"},
    {'input': f"Create a sequence based on this caption: {CAPTION_HOLDER}", 'output': f"Here it is: {MOTION_HOLDER}"},
    {'input': f"Can you generate a motion sequence for the caption: {CAPTION_HOLDER}?", 'output': f"This is the sequence: {MOTION_HOLDER}"},
    {'input': f"Produce a sequence of actions based on the description: {CAPTION_HOLDER}", 'output': f"The resulting motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Generate a motion sequence based on my caption: {CAPTION_HOLDER}", 'output': f"Okay, here is the motion: {MOTION_HOLDER}"},
    {'input': f"Visualize this described action: {CAPTION_HOLDER}", 'output': f"{MOTION_HOLDER}"},
    {'input': f"Create a sequence of actions based on this caption: {CAPTION_HOLDER}", 'output': f"The generated motion sequence is: {MOTION_HOLDER}"},
    {'input': f"Show me the motion sequence described here: {CAPTION_HOLDER}", 'output': f"The motion is: {MOTION_HOLDER}"},
    {'input': f"Can you visualize the motion described: {CAPTION_HOLDER}?", 'output': f"Sure, the motion sequence is: {MOTION_HOLDER}"},
]