from mmotion.utils.task.modality import AUDIO_HOLDER, MOTION_HOLDER

A2G_TEMPLATE = [
    {
        "input": f"A person is giving a speech, and the voice sounds like this: {AUDIO_HOLDER}, how might his body movements be?",
        "output": f"He might make movements like this: {MOTION_HOLDER}"},
    {
        "input": f"{AUDIO_HOLDER} Match this audio with visuals",
        "output": f"The speaker's co-speech gestures might be like this: {MOTION_HOLDER}"
    },
    {
        "input": f"The speaker is talking, and the audio sounds like this: {AUDIO_HOLDER}. What movements might they be making?",
        "output": f"Their movements could look like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this speech: {AUDIO_HOLDER}. How might the speaker be moving while speaking?",
     "output": f"The speaker might make gestures like this: {MOTION_HOLDER}"},
    {"input": f"This is the sound of a person giving a talk: {AUDIO_HOLDER}. What are their likely gestures?",
     "output": f"The likely movements are: {MOTION_HOLDER}"},
    {"input": f"While delivering this speech: {AUDIO_HOLDER}, what movements might accompany the speaker's words?",
     "output": f"The accompanying movements might be: {MOTION_HOLDER}"},
    {"input": f"Here is an audio clip of someone speaking: {AUDIO_HOLDER}. How do you think their body is moving?",
     "output": f"Their body might move in this way: {MOTION_HOLDER}"},
    {"input": f"Given this audio: {AUDIO_HOLDER}, how might the speaker's gestures appear?",
     "output": f"The speaker's gestures might look like this: {MOTION_HOLDER}"},
    {"input": f"During this talk: {AUDIO_HOLDER}, what motions might the person be performing?",
     "output": f"The person might perform these motions: {MOTION_HOLDER}"},
    {"input": f"The audio sounds like this: {AUDIO_HOLDER}. What movements could go along with the speech?",
     "output": f"These are the movements that could accompany the speech: {MOTION_HOLDER}"},
    {"input": f"With this speech audio: {AUDIO_HOLDER}, what are the possible body gestures?",
     "output": f"Possible body gestures might be: {MOTION_HOLDER}"},
    {"input": f"Here's the speaker's audio: {AUDIO_HOLDER}. What movements might you expect?",
     "output": f"You might expect movements like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this audio: {AUDIO_HOLDER}. How do you think the speaker's body is moving?",
     "output": f"The speaker might be moving like this: {MOTION_HOLDER}"},
    {"input": f"This is the sound of someone speaking: {AUDIO_HOLDER}. What gestures might they be making?",
     "output": f"They might be making gestures like this: {MOTION_HOLDER}"},
    {"input": f"Based on this audio: {AUDIO_HOLDER}, what might the speaker's movements look like?",
     "output": f"The speaker's movements might look like this: {MOTION_HOLDER}"},
    {"input": f"Given this sound: {AUDIO_HOLDER}, how do you think the speaker's gestures appear?",
     "output": f"The speaker's gestures might appear like this: {MOTION_HOLDER}"},
    {"input": f"The audio of a speech is provided: {AUDIO_HOLDER}. What actions might correspond to this sound?",
     "output": f"The corresponding actions might be: {MOTION_HOLDER}"},
    {"input": f"Here is a sample audio: {AUDIO_HOLDER}. How might the speaker be gesturing?",
     "output": f"The speaker might be gesturing like this: {MOTION_HOLDER}"},
    {"input": f"With this audio: {AUDIO_HOLDER}, how do you think the person's body language is?",
     "output": f"The body language might resemble this: {MOTION_HOLDER}"},
    {"input": f"Listen to this clip of a person speaking: {AUDIO_HOLDER}. What might their gestures look like?",
     "output": f"Their gestures might look like this: {MOTION_HOLDER}"},
    {
        "input": f"A person is giving a presentation, and the voice sounds like this: {AUDIO_HOLDER}. What body movements might they be making?",
        "output": f"They might be making these body movements: {MOTION_HOLDER}"},
    {"input": f"While this speaker talks: {AUDIO_HOLDER}, what are their possible motions?",
     "output": f"The speaker's motions might be: {MOTION_HOLDER}"},
    {"input": f"Here’s a speech clip: {AUDIO_HOLDER}. How might the speaker be gesturing?",
     "output": f"The speaker’s gestures could look like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this speech: {AUDIO_HOLDER}. What movements do you think accompany it?",
     "output": f"The movements accompanying it might be: {MOTION_HOLDER}"},
    {"input": f"The speaker is talking and the audio is: {AUDIO_HOLDER}. What might their body movements look like?",
     "output": f"Their body movements might look like this: {MOTION_HOLDER}"},
    {"input": f"This is the sound of someone giving a lecture: {AUDIO_HOLDER}. What are their likely movements?",
     "output": f"The likely movements are: {MOTION_HOLDER}"},
    {"input": f"A person is speaking, and the voice sounds like this: {AUDIO_HOLDER}. How might they be moving?",
     "output": f"They might be moving like this: {MOTION_HOLDER}"},
    {"input": f"This is a speech recording: {AUDIO_HOLDER}. What kind of movements could the speaker be making?",
     "output": f"The speaker could be making these movements: {MOTION_HOLDER}"},
    {
        "input": f"The audio for this speech sounds like: {AUDIO_HOLDER}. What kind of body language might the speaker exhibit?",
        "output": f"The speaker might exhibit this body language: {MOTION_HOLDER}"},
    {"input": f"Based on the following audio: {AUDIO_HOLDER}, what gestures might be seen?",
     "output": f"The speaker's gestures might look like this: {MOTION_HOLDER}"},
    {"input": f"While giving a talk, the speaker's voice is: {AUDIO_HOLDER}. What movements might accompany this?",
     "output": f"Accompanying movements could be: {MOTION_HOLDER}"},
    {"input": f"This is the audio of someone presenting: {AUDIO_HOLDER}. What gestures might go with it?",
     "output": f"The gestures could be: {MOTION_HOLDER}"},
    {"input": f"Listen to this talk: {AUDIO_HOLDER}. What movements might the speaker perform?",
     "output": f"The speaker might perform movements like these: {MOTION_HOLDER}"},
    {"input": f"A speaker is delivering a speech: {AUDIO_HOLDER}. What movements might be seen?",
     "output": f"You might see movements like these: {MOTION_HOLDER}"},
    {"input": f"This is what the speaker sounds like: {AUDIO_HOLDER}. How might the speaker be moving?",
     "output": f"The speaker might be moving in this way: {MOTION_HOLDER}"},
    {"input": f"During this speech: {AUDIO_HOLDER}, what body language might the speaker have?",
     "output": f"The speaker's body language might look like this: {MOTION_HOLDER}"},
    {"input": f"This is the sound of someone talking: {AUDIO_HOLDER}. What might their body gestures be?",
     "output": f"Their body gestures might be like this: {MOTION_HOLDER}"},
    {"input": f"Given the audio: {AUDIO_HOLDER}, how might the speaker's movements appear?",
     "output": f"The speaker's movements might appear like this: {MOTION_HOLDER}"},
    {"input": f"Here is the speaker’s voice: {AUDIO_HOLDER}. What gestures could be expected?",
     "output": f"The gestures could be expected to look like this: {MOTION_HOLDER}"},
    {
        "input": f"A person is delivering a presentation and the voice sounds like this: {AUDIO_HOLDER}. How might their gestures be?",
        "output": f"Their gestures might look like this: {MOTION_HOLDER}"},
    {"input": f"This person is giving a talk: {AUDIO_HOLDER}. How do you think their body is moving?",
     "output": f"Their body might be moving like this: {MOTION_HOLDER}"},
    {"input": f"Based on this sound clip: {AUDIO_HOLDER}, what movements might the speaker make?",
     "output": f"The speaker might make movements like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this audio of a person speaking: {AUDIO_HOLDER}. How might the speaker be gesturing?",
     "output": f"The speaker might gesture like this: {MOTION_HOLDER}"},
    {"input": f"The speaker's voice sounds like this: {AUDIO_HOLDER}. What movements might match?",
     "output": f"The matching movements might be like this: {MOTION_HOLDER}"},
    {"input": f"Here’s a person speaking: {AUDIO_HOLDER}. How might they be moving during the speech?",
     "output": f"Their movements during the speech might be: {MOTION_HOLDER}"},
    {"input": f"This is the sound of someone giving a talk: {AUDIO_HOLDER}. How do you think their gestures appear?",
     "output": f"Their gestures might appear like this: {MOTION_HOLDER}"},
    {"input": f"While giving this talk: {AUDIO_HOLDER}, what gestures might the speaker use?",
     "output": f"The speaker might use gestures like this: {MOTION_HOLDER}"},
    {"input": f"This audio sounds like: {AUDIO_HOLDER}. How might the speaker's movements look?",
     "output": f"The speaker's movements might look like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this speaker's voice: {AUDIO_HOLDER}. What movements do you think they are making?",
     "output": f"They might be making movements like this: {MOTION_HOLDER}"},
    {"input": f"Here's an audio clip of a speech: {AUDIO_HOLDER}. How might the speaker's gestures be?",
     "output": f"The speaker's gestures might be like this: {MOTION_HOLDER}"},
    {"input": f"During this audio speech: {AUDIO_HOLDER}, what gestures might the speaker have?",
     "output": f"The gestures might look like this: {MOTION_HOLDER}"},
    {"input": f"This person is giving a speech: {AUDIO_HOLDER}. What body language might they show?",
     "output": f"The body language might be: {MOTION_HOLDER}"},
    {"input": f"While delivering a talk: {AUDIO_HOLDER}, what movements could the speaker make?",
     "output": f"The speaker could make these movements: {MOTION_HOLDER}"},
    {"input": f"This audio is from a speech: {AUDIO_HOLDER}. How might the speaker's body gestures appear?",
     "output": f"The body gestures might appear like this: {MOTION_HOLDER}"},
    {
        "input": f"A person is speaking, and the voice sounds like this: {AUDIO_HOLDER}. What might their co-speech gestures be?",
        "output": f"The co-speech gestures might be like this: {MOTION_HOLDER}"},
    {"input": f"Listen to the speaker: {AUDIO_HOLDER}. What movements might match this speech?",
     "output": f"The movements that might match are: {MOTION_HOLDER}"},
    {"input": f"This is a speaker's voice: {AUDIO_HOLDER}. How might the speaker's actions be?",
     "output": f"The speaker's actions might be like this: {MOTION_HOLDER}"},
    {"input": f"Listen to the following audio: {AUDIO_HOLDER}. What body language might go with this speech?",
     "output": f"The body language might look like this: {MOTION_HOLDER}"},
    {"input": f"This speaker's audio sounds like: {AUDIO_HOLDER}. How might their gestures be?",
     "output": f"The gestures might be: {MOTION_HOLDER}"},
    {"input": f"This person is giving a talk: {AUDIO_HOLDER}. What movements might they be making?",
     "output": f"They might be making these movements: {MOTION_HOLDER}"},
    {"input": f"The speaker's voice in this clip sounds like: {AUDIO_HOLDER}. What body language could they have?",
     "output": f"The body language could look like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this speech audio: {AUDIO_HOLDER}. How do you think the speaker's body is moving?",
     "output": f"The speaker's body might be moving like this: {MOTION_HOLDER}"},
    {"input": f"This is what the speaker sounds like: {AUDIO_HOLDER}. How might their movements be?",
     "output": f"The movements might be like this: {MOTION_HOLDER}"},
    {"input": f"The audio sounds like this: {AUDIO_HOLDER}. What gestures might the speaker use?",
     "output": f"The speaker might use gestures like this: {MOTION_HOLDER}"},
    {"input": f"While speaking, the person sounds like this: {AUDIO_HOLDER}. What movements might they make?",
     "output": f"They might make movements like this: {MOTION_HOLDER}"},
    {"input": f"A speaker is presenting, and the voice sounds like: {AUDIO_HOLDER}. How might their body move?",
     "output": f"Their body might move like this: {MOTION_HOLDER}"},
    {"input": f"Listen to this clip of someone speaking: {AUDIO_HOLDER}. What gestures might go along with it?",
     "output": f"The gestures that go along with it might be: {MOTION_HOLDER}"},
    {"input": f"During this speech: {AUDIO_HOLDER}, how do you think the speaker is moving?",
     "output": f"The speaker might be moving in this way: {MOTION_HOLDER}"},
    {"input": f"Here's the voice of a speaker: {AUDIO_HOLDER}. How might they move?",
     "output": f"Their movements might look like this: {MOTION_HOLDER}"},
    {"input": f"This audio clip sounds like: {AUDIO_HOLDER}. What movements might accompany the speaker's words?",
     "output": f"Accompanying movements might be like this: {MOTION_HOLDER}"},
    {"input": f"The sound of this speech is: {AUDIO_HOLDER}. What might the speaker's body language be?",
     "output": f"The body language might resemble this: {MOTION_HOLDER}"},
    {"input": f"Listen to this audio speech: {AUDIO_HOLDER}. How do you think the speaker gestures?",
     "output": f"The speaker might gesture like this: {MOTION_HOLDER}"},
    {"input": f"Based on the audio: {AUDIO_HOLDER}, how might the speaker be gesturing?",
     "output": f"The speaker might gesture like this: {MOTION_HOLDER}"},
    {"input": f"Here's an audio recording: {AUDIO_HOLDER}. What body movements might the speaker have?",
     "output": f"The body movements might look like this: {MOTION_HOLDER}"},
    {"input": f"This person is talking: {AUDIO_HOLDER}. How do you think their gestures look?",
     "output": f"The gestures might look like this: {MOTION_HOLDER}"},
    {"input": f"The speaker's voice is: {AUDIO_HOLDER}. What kind of movements might they be making?",
     "output": f"The movements might be like this: {MOTION_HOLDER}"},
    {"input": f"Here is a speaker's audio: {AUDIO_HOLDER}. What gestures might match the audio?",
     "output": f"The matching gestures might be: {MOTION_HOLDER}"},
    {"input": f"This audio clip is from a talk: {AUDIO_HOLDER}. How might the speaker move?",
     "output": f"The speaker might move like this: {MOTION_HOLDER}"},
    {"input": f"This is a speaker’s voice: {AUDIO_HOLDER}. What gestures could accompany this voice?",
     "output": f"The accompanying gestures might be: {MOTION_HOLDER}"},
    {
        "input": f"The person is speaking, and the voice sounds like this: {AUDIO_HOLDER}. What body language might they display?",
        "output": f"They might display body language like this: {MOTION_HOLDER}"},
    {
        "input": f"The speaker is giving a speech, and the audio sounds like: {AUDIO_HOLDER}. What gestures might they perform?",
        "output": f"The gestures might be like this: {MOTION_HOLDER}"},
    {"input": f"While this person speaks: {AUDIO_HOLDER}, how do you think their movements look?",
     "output": f"Their movements might look like this: {MOTION_HOLDER}"}
]
